services:
  - type: web
    name: wellora-ai-healthcare
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: GEMINI_API_KEY
        value: AIzaSyCCy99Oh-TrbsYlBlW0HGfesESMB7eS50k
    healthCheckPath: /health

